vich_uploader:
    db_driver: orm

    # metadata:
    #     type: attribute

    mappings:
       book_cover_picture:
           uri_prefix: /images/book-cover-picture
           upload_destination: '%kernel.project_dir%/public/images/book-cover-picture'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
