vich_uploader:
    db_driver: orm

    # metadata:
    #     type: attribute

    mappings:
       book_cover_picture:
           uri_prefix: images/bookCover
           upload_destination: '%kernel.project_dir%/public/images/bookCover'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
